[project]
name = "tri-oo-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ddgs>=9.4.3",
    "openai>=1.90.0",
    "rich>=13.0.0",
]

[dependency-groups]
vllm = [
    "vllm>=0.10.0",
]
